# Generated by Django 3.2.18 on 2023-04-13 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0002_alter_portfoliocrypto_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionToken',
            new_name='PasswordResetToken',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
    ]
