# Generated by Django 5.2.12 on 2026-03-11 18:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('market_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('market_rank', 'name'),
            },
        ),
    ]
